name: Windows (Vulkan)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.189.2/windows/VulkanSDK-1.2.189.2-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("--da", "--al", "-c", "in");
          $installer.WaitForExit();
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Unpack v8_monolith
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: v8/libraries/win32/release/v8_monolith.7z
        pathTarget: v8/libraries/win32/release/
    - name: Compile
      run: Kinc/make -v vs2022 -g vulkan --compile
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: krom_windows_vulkan
        path: Deployment
